
ZZZ-SeeInput-Outputs:
  Html: 
    File: D:/Junk/SimReport.html
    View: Essential
    Iterations: [0, 5000, 9999] 

  Excel: 
    File: D:/Junk/SimReport.xlsx
    View: Essential

Views:
  
  Debug: [
    Year, Age, JanPreTax, JanPostTax, 
    MTROrdInc, MTRCapGain, MTRState,
    TaxPCT, TaxPCTFed, TaxPCTState,
    PYTaxes,
    MXInf, MXFedInf, MXNJInf,
    InflationRate
    ]

