
Outputs:
  Html: 
    File: D:/Junk/SimReport-AFTER-Decoupling.html
    View: Debug
    ZZIterations: [0, 5000, 9999] 

  Excel: 
    File: D:/Junk/SimReport-AFTER-Decoupling.xlsx
    View: Essential

Views:
  
  Debug: [

        Year,             
        Age,              

        JanNet,           
        DecNet,           

        FedAGI,           
        FedTax,           
        StaAGI,           
        StaTax,           
        Taxes,            

        Infl,
        MXInf,            
        MXInfFed,         
        MXInfSta,         

        ROI,              
        AnnROI,           
        RealCAGR,         
    ]

